// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace TattoStudio.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ConectividadExternaVeriFactuYGoogleCalendarFase6Feature : object, global::Xunit.IClassFixture<ConectividadExternaVeriFactuYGoogleCalendarFase6Feature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Conectividad Externa — VeriFactu y Google Calendar (Fase 6)", @"  Generación de cadena criptográfica SHA-256 para el Registro VeriFactu (AEAT) y
  sincronización asíncrona con Google Calendar vía eventos de dominio MediatR.
  REG-06-01: Cada factura almacena el SHA-256 de los datos críticos de la anterior,
             formando una cadena inmutable de libro mayor.
  REG-06-02: Si el envío a AEAT falla, AeataStatus queda en PendienteEnvio (0) y un
             BackgroundService reintenta cada 15 minutos sin bloquear al usuario.
  REG-06-03: La creación de citas dispara un AppointmentCreatedEvent procesado de
             forma asíncrona; el fallo de sincronización nunca revierte la cita.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Billing.feature"
#line hidden
        
        public ConectividadExternaVeriFactuYGoogleCalendarFase6Feature(ConectividadExternaVeriFactuYGoogleCalendarFase6Feature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 12
  #line hidden
#line 13
    await testRunner.GivenAsync("la API está en ejecución", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
    await testRunner.AndAsync("existe un usuario registrado con email \"admin@tattostudio.com\" y password \"Admin1" +
                    "23!\" y rol 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync("estoy autenticado con email \"admin@tattostudio.com\" y password \"Admin123!\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync("existe un artista de prueba para citas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.AndAsync("existe un cliente de prueba para citas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync("existe una cita pendiente el \"2099-12-15\" a las \"10:00\" UTC con duración 2 horas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync("el consentimiento de la última cita ha sido firmado", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.AndAsync("existe un pago de \"200.00\" tipo 1 método 0 en la última cita", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Billing.feature.ndjson", 8);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Emitir primera factura genera número secuencial con hash vacío")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Conectividad Externa — VeriFactu y Google Calendar (Fase 6)")]
        [global::Xunit.TraitAttribute("Description", "Emitir primera factura genera número secuencial con hash vacío")]
        public async global::System.Threading.Tasks.Task EmitirPrimeraFacturaGeneraNumeroSecuencialConHashVacio()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Emitir primera factura genera número secuencial con hash vacío", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
  await this.FeatureBackgroundAsync();
#line hidden
#line 25
    await testRunner.WhenAsync("envío POST autenticado a \"/api/billing/invoices\" con el último pago", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 27
    await testRunner.AndAsync("el cuerpo de la respuesta contiene el campo \"invoiceNumber\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
    await testRunner.AndAsync("el cuerpo de la respuesta contiene el campo \"previousInvoiceHash\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="REG-06-01 Segunda factura almacena el hash SHA-256 de la primera")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Conectividad Externa — VeriFactu y Google Calendar (Fase 6)")]
        [global::Xunit.TraitAttribute("Description", "REG-06-01 Segunda factura almacena el hash SHA-256 de la primera")]
        public async global::System.Threading.Tasks.Task REG_06_01SegundaFacturaAlmacenaElHashSHA_256DeLaPrimera()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("REG-06-01 Segunda factura almacena el hash SHA-256 de la primera", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
  await this.FeatureBackgroundAsync();
#line hidden
#line 31
    await testRunner.GivenAsync("existe una factura emitida para el último pago", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 32
    await testRunner.AndAsync("existe un pago de \"150.00\" tipo 0 método 1 en la última cita", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
    await testRunner.WhenAsync("envío POST autenticado a \"/api/billing/invoices\" con el último pago", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 35
    await testRunner.AndAsync("el cuerpo de la respuesta contiene previousInvoiceHash no vacío", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Consultar estado VeriFactu de factura existente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Conectividad Externa — VeriFactu y Google Calendar (Fase 6)")]
        [global::Xunit.TraitAttribute("Description", "Consultar estado VeriFactu de factura existente")]
        public async global::System.Threading.Tasks.Task ConsultarEstadoVeriFactuDeFacturaExistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consultar estado VeriFactu de factura existente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
  await this.FeatureBackgroundAsync();
#line hidden
#line 38
    await testRunner.GivenAsync("existe una factura emitida para el último pago", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 39
    await testRunner.WhenAsync("envío GET autenticado al estado VeriFactu de la última factura", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 41
    await testRunner.AndAsync("el cuerpo de la respuesta contiene el campo \"aeataStatus\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
    await testRunner.AndAsync("el cuerpo de la respuesta contiene el campo \"invoiceNumber\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Consultar estado VeriFactu de factura inexistente devuelve 404")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Conectividad Externa — VeriFactu y Google Calendar (Fase 6)")]
        [global::Xunit.TraitAttribute("Description", "Consultar estado VeriFactu de factura inexistente devuelve 404")]
        public async global::System.Threading.Tasks.Task ConsultarEstadoVeriFactuDeFacturaInexistenteDevuelve404()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consultar estado VeriFactu de factura inexistente devuelve 404", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
  await this.FeatureBackgroundAsync();
#line hidden
#line 45
    await testRunner.WhenAsync("envío GET autenticado a \"/api/billing/invoices/00000000-0000-0000-0000-0000000000" +
                        "00/verifactu-status\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 46
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Guardar tokens OAuth de Google Calendar")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Conectividad Externa — VeriFactu y Google Calendar (Fase 6)")]
        [global::Xunit.TraitAttribute("Description", "Guardar tokens OAuth de Google Calendar")]
        public async global::System.Threading.Tasks.Task GuardarTokensOAuthDeGoogleCalendar()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Guardar tokens OAuth de Google Calendar", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 50
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "AccessToken",
                            "RefreshToken",
                            "ExpiresAt"});
                table13.AddRow(new string[] {
                            "acc-token",
                            "ref-token",
                            "2099-12-31T00:00:00Z"});
#line 51
    await testRunner.WhenAsync("envío POST autenticado a \"/api/integrations/google-auth\" con los tokens:", ((string)(null)), table13, "When ");
#line hidden
#line 54
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="REG-06-03 Crear cita no falla cuando Google Calendar no está configurado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Conectividad Externa — VeriFactu y Google Calendar (Fase 6)")]
        [global::Xunit.TraitAttribute("Description", "REG-06-03 Crear cita no falla cuando Google Calendar no está configurado")]
        public async global::System.Threading.Tasks.Task REG_06_03CrearCitaNoFallaCuandoGoogleCalendarNoEstaConfigurado()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("REG-06-03 Crear cita no falla cuando Google Calendar no está configurado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 56
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "DateTime",
                            "DurationHours",
                            "DepositAmount"});
                table14.AddRow(new string[] {
                            "2099-12-17T10:00:00Z",
                            "2",
                            "0.00"});
#line 57
    await testRunner.WhenAsync("envío POST autenticado a \"/api/appointments\" con datos de la cita:", ((string)(null)), table14, "When ");
#line hidden
#line 60
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ConectividadExternaVeriFactuYGoogleCalendarFase6Feature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ConectividadExternaVeriFactuYGoogleCalendarFase6Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
