// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace TattoStudio.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class FinanzasYLogisticaPagosCierreYStockFase5Feature : object, global::Xunit.IClassFixture<FinanzasYLogisticaPagosCierreYStockFase5Feature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Finanzas y Logística — Pagos, Cierre y Stock (Fase 5)", @"  Gestión de cobros parciales y totales, cierre atómico de citas con registro
  automático de comisión al artista, descuento de inventario y alertas de stock bajo.
  REG-05-01: El cierre es transaccional — verifica consentimiento firmado,
             registra comisión (Total Pagos * CommissionPercentage / 100),
             resta stock y marca la cita como Completada. Todo o nada.
  REG-05-02: Si CurrentQuantity <= MinThreshold tras descontar stock,
             la respuesta incluye RequiresRestock: true.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Finance.feature"
#line hidden
        
        public FinanzasYLogisticaPagosCierreYStockFase5Feature(FinanzasYLogisticaPagosCierreYStockFase5Feature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 11
  #line hidden
#line 12
    await testRunner.GivenAsync("la API está en ejecución", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
    await testRunner.AndAsync("existe un usuario registrado con email \"finance@tattostudio.com\" y password \"Admi" +
                    "n123!\" y rol 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
    await testRunner.AndAsync("estoy autenticado con email \"finance@tattostudio.com\" y password \"Admin123!\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync("existe un artista de prueba para citas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync("existe un cliente de prueba para citas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.AndAsync("existe una cita pendiente el \"2099-12-15\" a las \"10:00\" UTC con duración 2 horas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync("el consentimiento de la última cita ha sido firmado", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync("existe un ítem de stock con nombre \"Tinta Negra\" cantidad \"10\" y umbral mínimo \"3" +
                    "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Finance.feature.ndjson", 12);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Registrar una seña en la cita")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Finanzas y Logística — Pagos, Cierre y Stock (Fase 5)")]
        [global::Xunit.TraitAttribute("Description", "Registrar una seña en la cita")]
        public async global::System.Threading.Tasks.Task RegistrarUnaSenaEnLaCita()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar una seña en la cita", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 25
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "Amount",
                            "Type",
                            "Method"});
                table22.AddRow(new string[] {
                            "100.00",
                            "0",
                            "0"});
#line 26
    await testRunner.WhenAsync("envío POST autenticado a \"/api/payments\" con los datos de pago:", ((string)(null)), table22, "When ");
#line hidden
#line 29
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 30
    await testRunner.AndAsync("el cuerpo de la respuesta contiene un Id de tipo Guid válido", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Registrar el pago final de la cita")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Finanzas y Logística — Pagos, Cierre y Stock (Fase 5)")]
        [global::Xunit.TraitAttribute("Description", "Registrar el pago final de la cita")]
        public async global::System.Threading.Tasks.Task RegistrarElPagoFinalDeLaCita()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registrar el pago final de la cita", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 32
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "Amount",
                            "Type",
                            "Method"});
                table23.AddRow(new string[] {
                            "350.00",
                            "1",
                            "2"});
#line 33
    await testRunner.WhenAsync("envío POST autenticado a \"/api/payments\" con los datos de pago:", ((string)(null)), table23, "When ");
#line hidden
#line 36
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 37
    await testRunner.AndAsync("el cuerpo de la respuesta contiene un Id de tipo Guid válido", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Rechazar pago con importe cero")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Finanzas y Logística — Pagos, Cierre y Stock (Fase 5)")]
        [global::Xunit.TraitAttribute("Description", "Rechazar pago con importe cero")]
        public async global::System.Threading.Tasks.Task RechazarPagoConImporteCero()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Rechazar pago con importe cero", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "Amount",
                            "Type",
                            "Method"});
                table24.AddRow(new string[] {
                            "0.00",
                            "0",
                            "0"});
#line 40
    await testRunner.WhenAsync("envío POST autenticado a \"/api/payments\" con los datos de pago:", ((string)(null)), table24, "When ");
#line hidden
#line 43
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 44
    await testRunner.AndAsync("el cuerpo de error contiene el mensaje \"positivo\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Rechazar pago en cita inexistente devuelve 404")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Finanzas y Logística — Pagos, Cierre y Stock (Fase 5)")]
        [global::Xunit.TraitAttribute("Description", "Rechazar pago en cita inexistente devuelve 404")]
        public async global::System.Threading.Tasks.Task RechazarPagoEnCitaInexistenteDevuelve404()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Rechazar pago en cita inexistente devuelve 404", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "Amount",
                            "Type",
                            "Method"});
                table25.AddRow(new string[] {
                            "50.00",
                            "0",
                            "0"});
#line 47
    await testRunner.WhenAsync("envío POST autenticado a \"/api/payments\" en la cita \"00000000-0000-0000-0000-0000" +
                        "00000000\" con los datos:", ((string)(null)), table25, "When ");
#line hidden
#line 50
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="REG-05-01 Completar cita ejecuta flujo transaccional completo")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Finanzas y Logística — Pagos, Cierre y Stock (Fase 5)")]
        [global::Xunit.TraitAttribute("Description", "REG-05-01 Completar cita ejecuta flujo transaccional completo")]
        public async global::System.Threading.Tasks.Task REG_05_01CompletarCitaEjecutaFlujoTransaccionalCompleto()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("REG-05-01 Completar cita ejecuta flujo transaccional completo", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 56
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 57
    await testRunner.WhenAsync("envío POST autenticado para completar la última cita usando el ítem \"Tinta Negra\"" +
                        " con cantidad 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 59
    await testRunner.AndAsync("el cuerpo de la respuesta contiene el estado \"Completada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
    await testRunner.AndAsync("el cuerpo de la respuesta contiene el campo \"commissionAmount\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
    await testRunner.AndAsync("el cuerpo de la respuesta contiene requiresRestock false", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="REG-05-01 Rechazar cierre si el consentimiento no está firmado")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Finanzas y Logística — Pagos, Cierre y Stock (Fase 5)")]
        [global::Xunit.TraitAttribute("Description", "REG-05-01 Rechazar cierre si el consentimiento no está firmado")]
        public async global::System.Threading.Tasks.Task REG_05_01RechazarCierreSiElConsentimientoNoEstaFirmado()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("REG-05-01 Rechazar cierre si el consentimiento no está firmado", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 63
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 64
    await testRunner.GivenAsync("existe una cita pendiente el \"2099-12-20\" a las \"14:00\" UTC con duración 2 horas", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 65
    await testRunner.WhenAsync("envío POST autenticado para completar la última cita usando el ítem \"Tinta Negra\"" +
                        " con cantidad 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 400", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 67
    await testRunner.AndAsync("el cuerpo de error contiene el mensaje \"consentimiento\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Rechazar cierre de cita inexistente devuelve 404")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Finanzas y Logística — Pagos, Cierre y Stock (Fase 5)")]
        [global::Xunit.TraitAttribute("Description", "Rechazar cierre de cita inexistente devuelve 404")]
        public async global::System.Threading.Tasks.Task RechazarCierreDeCitaInexistenteDevuelve404()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Rechazar cierre de cita inexistente devuelve 404", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 69
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "StockItemName",
                            "Quantity"});
                table26.AddRow(new string[] {
                            "Tinta Negra",
                            "1"});
#line 70
    await testRunner.WhenAsync("envío POST autenticado a \"/api/appointments/00000000-0000-0000-0000-000000000000/" +
                        "complete\" con items:", ((string)(null)), table26, "When ");
#line hidden
#line 73
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="REG-05-02 Alerta de stock bajo al cerrar cita")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Finanzas y Logística — Pagos, Cierre y Stock (Fase 5)")]
        [global::Xunit.TraitAttribute("Description", "REG-05-02 Alerta de stock bajo al cerrar cita")]
        public async global::System.Threading.Tasks.Task REG_05_02AlertaDeStockBajoAlCerrarCita()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("REG-05-02 Alerta de stock bajo al cerrar cita", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 79
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 80
    await testRunner.GivenAsync("existe un ítem de stock con nombre \"Tinta Roja\" cantidad \"2\" y umbral mínimo \"3\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 81
    await testRunner.AndAsync("existe una cita pendiente el \"2099-12-16\" a las \"11:00\" UTC con duración 2 horas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
    await testRunner.AndAsync("el consentimiento de la última cita ha sido firmado", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
    await testRunner.WhenAsync("envío POST autenticado para completar la última cita usando el ítem \"Tinta Roja\" " +
                        "con cantidad 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 84
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 85
    await testRunner.AndAsync("el cuerpo de la respuesta contiene requiresRestock true", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Consultar ítems con stock bajo")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Finanzas y Logística — Pagos, Cierre y Stock (Fase 5)")]
        [global::Xunit.TraitAttribute("Description", "Consultar ítems con stock bajo")]
        public async global::System.Threading.Tasks.Task ConsultarItemsConStockBajo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consultar ítems con stock bajo", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 87
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 88
    await testRunner.GivenAsync("existe un ítem de stock con nombre \"Agujas 7M\" cantidad \"1\" y umbral mínimo \"5\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 89
    await testRunner.WhenAsync("envío GET autenticado a \"/api/stock/low-inventory\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 90
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 91
    await testRunner.AndAsync("el cuerpo de la respuesta es una lista JSON", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
    await testRunner.AndAsync("la lista contiene al menos un ítem con requiresRestock true", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Stock por encima del umbral no aparece en alertas")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Finanzas y Logística — Pagos, Cierre y Stock (Fase 5)")]
        [global::Xunit.TraitAttribute("Description", "Stock por encima del umbral no aparece en alertas")]
        public async global::System.Threading.Tasks.Task StockPorEncimaDelUmbralNoApareceEnAlertas()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Stock por encima del umbral no aparece en alertas", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 94
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 11
  await this.FeatureBackgroundAsync();
#line hidden
#line 95
    await testRunner.WhenAsync("envío GET autenticado a \"/api/stock/low-inventory\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 96
    await testRunner.ThenAsync("la respuesta tiene el código HTTP 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 97
    await testRunner.AndAsync("el cuerpo de la respuesta es una lista JSON", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
    await testRunner.AndAsync("la lista no contiene el ítem \"Tinta Negra\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await FinanzasYLogisticaPagosCierreYStockFase5Feature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await FinanzasYLogisticaPagosCierreYStockFase5Feature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
